EXPIRY_SECONDS_FOR_HOUR = 60 * 60
EXPIRY_SECONDS_FOR_DAY = 60 * 60 * 24
EXPIRY_SECONDS_FOR_WEEK = 60 * 60 * 24 * 7
EXPIRY_SECONDS_FOR_MONTH = 60 * 60 * 24 * 31
EXPIRY_SECONDS_FOR_YEAR = 60 * 60 * 24 * 365

EXPIRY_SECONDS_FOR_TIME_UNITS = {
    'h': EXPIRY_SECONDS_FOR_HOUR,
    'd': EXPIRY_SECONDS_FOR_DAY,
    'w': EXPIRY_SECONDS_FOR_WEEK,
    'm': EXPIRY_SECONDS_FOR_MONTH,
    'y': EXPIRY_SECONDS_FOR_YEAR,
}

ITEM_TYPE_CONTRIBUTION = 'contribution'
ITEM_TYPE_DONATION = 'donation'
ITEM_TYPE_POLITICAL_CONTRIBUTION = 'political'
