language: python
install:
  - pip install tox
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=cov
  - TOX_ENV=flake8
script:
  - tox -e $TOX_ENV
matrix:
  fast_finish: true
  allow_failures:
    - env: TOX_ENV=flake8
