language: python
sudo: false
install:
  - pip install tox==2.1.1 coveralls
env:
  - TOX_ENV=py27
  - TOX_ENV=py33
  - TOX_ENV=py34
  - TOX_ENV=flake8
  - TOX_ENV=pydocstyle
script:
  - tox -e $TOX_ENV
  - coveralls
matrix:
  fast_finish: true
  include:
    - python: 3.5
      env:
        - TOX_ENV=py35
