language: python
install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//./},flake8,pydocstyle
  - coveralls
matrix:
  fast_finish: true
  include:
    - python: 2.7
      dist: trusty
      sudo: false
    - python: 3.4
      dist: trusty
      sudo: false
    - python: 3.5
      dist: trusty
      sudo: false
    - python: 3.6
      dist: trusty
      sudo: false
    - python: 3.7
      dist: xenial
      sudo: true
