language: python
python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5
  - 3.6
sudo: false
install:
  - pip install tox coveralls
script:
  - tox -e py${TRAVIS_PYTHON_VERSION//./},flake8,pydocstyle
  - coveralls
matrix:
  fast_finish: true
